module.exports.themeService = require('./theme.service')
module.exports.resService = require('./restaurant.service')
module.exports.branchService = require('./branch.service')
module.exports.branchUserService = require('./branchuser.service')
module.exports.subscriptionService = require('./subscription.service')